### ISSUE TITLE
Exclusion list is incorrect for new Android variants

### ISSUE THREAD

**Issue by barry-irvine** [bitrise-steplib/bitrise-step-android-build#39] opened 2022-05-11 08:47 UTC
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.0.2
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES / NO / NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

It looks like some of the Android gradle variants have been renamed (perhaps with Android Gradle Plugin 7.2.0) and therefore the exclusion list at line 90 in https://github.com/bitrise-steplib/bitrise-step-android-build/blob/master/step/step.go is insufficient.

For example there is no longer a task with the suffix `AndroidTestClasses` it is now `AndroidTestClassesToCompileJar`. I think simply adding `ClassesToCompileJar` to the exclusion list would fix it.

### Bitrise info

- Build URL: (https://app.bitrise.io/build/d6dca4f6-9a41-4159-8a21-9af4d9ac62b8)
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log: 

<details>
  <pre>
Could not determine the dependencies of task ':app:bundleDebugUnitTestClassesToCompileJar'.
  </pre>
</details>

### Steps to reproduce

1. Create a project using Android Chipmunk and Android Gradle Plugin 7.2.0
2. Try to generate an Android aab build

**Comment by lpusok** [comment] 2022-05-24 11:00
Hello @barry-irvine,
Thanks for reporting the issue, it seems the reason of the issue is indeed new tasks introduced in the Android Gradle Plugin. Looking into resolving this.
In the meanwhile please specify module and variant(s) explicitly like this:
``` 
- android-build:
      inputs:
      - module: app
      - variant: DemoRelease\nDemoDebug
 ```

**Comment by barry-irvine** [comment] 2022-06-07 11:04
Any news on this? AGP 7.2/Android Studio Chipmunk has been stable for almost a month now.

**Comment by barry-irvine** [comment] 2022-06-21 10:19
Still nothing? It's a one-line fix. Why is it taking so long? I am advising the head of mobile to look for an alternative CI tool given the fact that your development processes are so slow and do not keep up-to-date with the latest Android tooling. Putting all the module names in a multi-module project as the variants isn't really a workable workaround for us.

**Comment by rwbutler** [comment] 2022-07-12 09:54
Dear @lpusok,

Thank you for the response. Unfortunately, given the number of modules and variants we have in our project this isn't really a workable solution for us. We'd really appreciate if someone could advise on a timeline for a solution to this issue.

**Closed** 2022-07-14 11:55 UTC
